public enum PokemonType : String{
    case normal = "NORMAL"
    case fire = "FIRE"
    case water = "WATER"
    case grass = "GRASS"
    case electric = "ELECTRIC"
    case ice = "ICE"
    case fighting = "FIGHTING"
    case poison = "POISON"
    case ground = "GROUND"
    case flying = "FLYING"
    case psychic = "PSYCHIC"
    case bug = "BUG"
    case rock = "ROCK"
    case ghost = "GHOST"
    case dark = "DARK"
    case dragon = "DRAGON"
    case steel = "STEEL"
    case fairy = "FAIRY"
}
