public func typeEffectiveness(attackingType:PokemonType, defendingType:PokemonType?) -> Double{
    // Hideously ugly way to make a table, consider making a SQLITE3 table?
    switch defendingType{
    case .normal:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 1.6
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.0
        case .ghost:
            return 0.390625
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .fire:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 0.625
        case .water:
            return 1.6
        case .grass:
            return 0.625
        case .electric:
            return 1.0
        case .ice:
            return 0.625
        case .fighting:
            return 1.0
        case .poison:
            return 1.0
        case .ground:
            return 1.6
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 0.625
        case .rock:
            return 1.6
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 0.625
        case .fairy:
            return 0.625
        }
    case .water:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 0.625
        case .water:
            return 0.625
        case .grass:
            return 1.6
        case .electric:
            return 1.6
        case .ice:
            return 0.625
        case .fighting:
            return 1.0
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 0.625
        case .fairy:
            return 1.0
        }
    case .grass:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.6
        case .water:
            return 0.625
        case .grass:
            return 0.625
        case .electric:
            return 0.625
        case .ice:
            return 1.6
        case .fighting:
            return 1.0
        case .poison:
            return 1.6
        case .ground:
            return 0.625
        case .flying:
            return 1.6
        case .psychic:
            return 1.0
        case .bug:
            return 1.6
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .electric:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 0.625
        case .ice:
            return 1.0
        case .fighting:
            return 1.0
        case .poison:
            return 1.0
        case .ground:
            return 1.6
        case .flying:
            return 0.625
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 0.625
        case .fairy:
            return 1.0
        }
    case .ice:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.6
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 0.625
        case .fighting:
            return 1.6
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.6
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.6
        case .fairy:
            return 1.0
        }
    case .fighting:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 1.0
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.6
        case .psychic:
            return 1.6
        case .bug:
            return 0.625
        case .rock:
            return 0.625
        case .ghost:
            return 1.0
        case .dark:
            return 0.625
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.6
        }
    case .poison:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 0.625
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 0.625
        case .poison:
            return 0.625
        case .ground:
            return 1.6
        case .flying:
            return 1.0
        case .psychic:
            return 1.6
        case .bug:
            return 0.625
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 0.625
        }
    case .ground:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.6
        case .grass:
            return 1.6
        case .electric:
            return 0.390625
        case .ice:
            return 1.6
        case .fighting:
            return 1.0
        case .poison:
            return 0.625
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 0.625
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .flying:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 0.625
        case .electric:
            return 1.6
        case .ice:
            return 1.6
        case .fighting:
            return 0.625
        case .poison:
            return 1.0
        case .ground:
            return 0.390625
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 0.625
        case .rock:
            return 1.6
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .psychic:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 0.625
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 0.625
        case .bug:
            return 1.6
        case .rock:
            return 1.0
        case .ghost:
            return 1.6
        case .dark:
            return 1.6
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .bug:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.6
        case .water:
            return 1.0
        case .grass:
            return 0.625
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 0.625
        case .poison:
            return 1.0
        case .ground:
            return 0.625
        case .flying:
            return 1.6
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.6
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .rock:
        switch attackingType{
        case .normal:
            return 0.625
        case .fire:
            return 0.625
        case .water:
            return 1.6
        case .grass:
            return 1.6
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 1.6
        case .poison:
            return 0.625
        case .ground:
            return 1.6
        case .flying:
            return 0.625
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.0
        case .steel:
            return 1.6
        case .fairy:
            return 1.0
        }
    case .ghost:
        switch attackingType{
        case .normal:
            return 0.390625
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 0.390625
        case .poison:
            return 0.625
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 0.625
        case .rock:
            return 1.0
        case .ghost:
            return 1.6
        case .dark:
            return 1.6
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.0
        }
    case .dark:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 1.6
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 0.390625
        case .bug:
            return 1.6
        case .rock:
            return 1.0
        case .ghost:
            return 0.625
        case .dark:
            return 0.625
        case .dragon:
            return 1.0
        case .steel:
            return 1.0
        case .fairy:
            return 1.6
        }
    case .dragon:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 0.625
        case .water:
            return 0.625
        case .grass:
            return 0.625
        case .electric:
            return 0.625
        case .ice:
            return 1.6
        case .fighting:
            return 1.0
        case .poison:
            return 1.0
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 1.0
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 1.6
        case .steel:
            return 1.0
        case .fairy:
            return 1.6
        }
    case .steel:
        switch attackingType{
        case .normal:
            return 0.625
        case .fire:
            return 1.6
        case .water:
            return 1.0
        case .grass:
            return 0.625
        case .electric:
            return 1.0
        case .ice:
            return 0.625
        case .fighting:
            return 1.6
        case .poison:
            return 0.390625
        case .ground:
            return 1.6
        case .flying:
            return 0.625
        case .psychic:
            return 0.625
        case .bug:
            return 0.625
        case .rock:
            return 0.625
        case .ghost:
            return 1.0
        case .dark:
            return 1.0
        case .dragon:
            return 0.625
        case .steel:
            return 0.625
        case .fairy:
            return 0.625
        }
    case .fairy:
        switch attackingType{
        case .normal:
            return 1.0
        case .fire:
            return 1.0
        case .water:
            return 1.0
        case .grass:
            return 1.0
        case .electric:
            return 1.0
        case .ice:
            return 1.0
        case .fighting:
            return 0.625
        case .poison:
            return 1.6
        case .ground:
            return 1.0
        case .flying:
            return 1.0
        case .psychic:
            return 1.0
        case .bug:
            return 0.625
        case .rock:
            return 1.0
        case .ghost:
            return 1.0
        case .dark:
            return 0.625
        case .dragon:
            return 0.390625
        case .steel:
            return 1.6
        case .fairy:
            return 1.0
        }    
    case nil:
        return 1.0
    }
}
